Updating README.md
Params need to be LP_PASS instead of LP_PASSWORD when using command 
LP_ACCOUNT=1234567 LP_USER=BotUserName LP_PASS=b0tpa55word node examples/greeting-bot/greeting-bot.js
 if we use LP_PASSWORD it doesn't get authenticated and gives below error.
/home/ubuntu/node-agent-sdk/lib/AgentSDK.js:56
            throw new Error('missing token or user/password or assertion or appKey/secret/accessToken/accessTokenSecret params');
            ^

Error: missing token or user/password or assertion or appKey/secret/accessToken/accessTokenSecret params